export { default as Header } from "./Header";
export { default as HeaderV2 } from "./HeaderV2";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Footer } from "./Footer";
export { default as Carrusel } from "./Carrousel";
export { default as Hero } from "./Hero";
export { default as Card } from "./Card/SingleCard";
export { default as Cards } from "./Card/Cards";
export { default as Section } from "./Section";
export { default as Table } from "./Table";
export { default as Bienes } from "./Bienes";
export { default as BienesMaquinas } from "./BienesMaquinas";
export { default as Title } from "./Title";
export { default as SectionProvider } from "./SectionProvider/index";
export { default as SectionClients } from "./SectionClients/index";
export { default as SectionStaff } from "./SectionStaff/index.jsx";
export { default as BienesElementos } from "./BienesElementos";
export { default as BienesMobiliario } from "./BienesMobiliario";
export {default as Gastos} from "./Gastos";
export {default as ConstructionPage} from "./ConstructionPage/index"